feat: options to skip some files
tomasklaen/postcss-prune-var pull request #3
Opened 2023-05-13 06:19 UTC by birdgg

Sometimes, we need to skip files. 

For example, this [lib](https://github.com/vercel-labs/react-tweet) with nextjs, it put css variable in `theme.css` and use variable in other module css. Since these css files not be merged, postcss-prune-var will remove variable in theme.css, and cause a bug that other module css can not find variable.

ps: Sorry for my pool english.

2023-05-13 17:52 UTC, tomasklaen requested changes

2023-05-13 17:52 UTC, tomasklaen commented on README.md
> +use this option to exclude certain files or folders that would otherwise be scanned
- Space between title and description.
- Sentence starts with a capital letter and ends with a dot.

2023-05-13 17:52 UTC, tomasklaen commented on index.js
> +					record = { uses: 0, dependencies: new Set(), declarations: new Set() };
Don't modify existing white space. Same goes for new diffs below.

2023-05-13 17:52 UTC, tomasklaen commented on index.js
> +const path = require("path");
Add new line here. And remove spaces in `{ minimatch }`. I know I don't have any .prettierrc file, but let's be consistent with the rest of the existing file.

2023-05-13 17:52 UTC, tomasklaen commented
Is `skip` option name the convention in postcss plugin ecosystem?

2023-05-14 04:47 UTC, birdgg commented
> Is `skip` option name the convention in postcss plugin ecosystem?

I get the idea from [PurgeCSS](https://purgecss.com/configuration.html) `skippedContentGlobs` option

> - skippedContentGlobs
If you provide globs for the content parameter, you can use this option to exclude certain files or folders that would otherwise be scanned. Pass an array of globs matching items that should be excluded. (Note: this option has no effect if content is not globs.)

2023-05-14 09:56 UTC, tomasklaen commented
Fix the issue, and add a test for this. Create `fixtures` folder and add some css files there to test the filtering.

2023-05-14 10:52 UTC, birdgg commented
> Fix the issue, and add a test for this. Create `fixtures` folder and add some css files there to test the filtering.

Test added

2023-05-14 13:06 UTC, tomasklaen commented
Oh, I thought you're going to read the file with postcss. I see that they don't have such API (sorry, haven't touched it in a while). If we're just setting the path with `from` process() option, then we don't need fixtures. Sorry for the confusion.

2023-05-14 13:43 UTC, birdgg commented
Yeah, remove fixtures

2023-05-14 14:44 UTC, merged